version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "flet"
        versions: [">0.28.3"]
      - dependency-name: "flet-desktop"
        versions: [">0.28.3"]
    groups:
      pip:
        patterns: ["*"]
        exclude-patterns:
          - "flet"
          - "flet-desktop"
