"""add_updated_at_to_all_tables

Revision ID: 01ed9827755e
Revises: a1b2c3d4e5f6
Create Date: 2026-03-10 16:01:39.038937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01ed9827755e'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adj_factor', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('daily_indicators', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('daily_quotes', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('dividend', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('fina_audit', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('fina_forecast', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('fina_mainbz', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('financial_reports', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('index_daily', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('index_dailybasic', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('index_weight', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('limit_list', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('margin_daily', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('moneyflow_daily', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('moneyflow_hsgt', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('northbound_holding', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('pledge_stat', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('repurchase', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('shibor_daily', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('stk_holdernumber', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('stock_sync_status', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('suspend_d', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('top10_holders', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('top_list', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('trade_cal', sa.Column('updated_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_cal', 'updated_at')
    op.drop_column('top_list', 'updated_at')
    op.drop_column('top10_holders', 'updated_at')
    op.drop_column('suspend_d', 'updated_at')
    op.drop_column('stock_sync_status', 'updated_at')
    op.drop_column('stk_holdernumber', 'updated_at')
    op.drop_column('shibor_daily', 'updated_at')
    op.drop_column('repurchase', 'updated_at')
    op.drop_column('pledge_stat', 'updated_at')
    op.drop_column('northbound_holding', 'updated_at')
    op.drop_column('moneyflow_hsgt', 'updated_at')
    op.drop_column('moneyflow_daily', 'updated_at')
    op.drop_column('margin_daily', 'updated_at')
    op.drop_column('limit_list', 'updated_at')
    op.drop_column('index_weight', 'updated_at')
    op.drop_column('index_dailybasic', 'updated_at')
    op.drop_column('index_daily', 'updated_at')
    op.drop_column('financial_reports', 'updated_at')
    op.drop_column('fina_mainbz', 'updated_at')
    op.drop_column('fina_forecast', 'updated_at')
    op.drop_column('fina_audit', 'updated_at')
    op.drop_column('dividend', 'updated_at')
    op.drop_column('daily_quotes', 'updated_at')
    op.drop_column('daily_indicators', 'updated_at')
    op.drop_column('adj_factor', 'updated_at')
    # ### end Alembic commands ###
