"""initial_baseline_full

Revision ID: 367c382dbf28
Revises:
Create Date: 2026-03-04 20:57:13.832233

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "367c382dbf28"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adj_factor",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("trade_date", sa.String(), nullable=False),
        sa.Column("adj_factor", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("ts_code", "trade_date", name=op.f("pk_adj_factor")),
    )
    with op.batch_alter_table("adj_factor", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_adj_factor_trade_date"), ["trade_date"], unique=False,
        )

    op.create_table(
        "block_trade",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("trade_date", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("buyer", sa.String(), nullable=False),
        sa.Column("seller", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint(
            "ts_code", "trade_date", "buyer", "seller", name=op.f("pk_block_trade"),
        ),
    )
    op.create_table(
        "daily_indicators",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("trade_date", sa.String(), nullable=False),
        sa.Column("pe", sa.Float(), nullable=True),
        sa.Column("pe_ttm", sa.Float(), nullable=True),
        sa.Column("pb", sa.Float(), nullable=True),
        sa.Column("ps", sa.Float(), nullable=True),
        sa.Column("ps_ttm", sa.Float(), nullable=True),
        sa.Column("dv_ratio", sa.Float(), nullable=True),
        sa.Column("dv_ttm", sa.Float(), nullable=True),
        sa.Column("total_mv", sa.Float(), nullable=True),
        sa.Column("circ_mv", sa.Float(), nullable=True),
        sa.Column("total_share", sa.Float(), nullable=True),
        sa.Column("float_share", sa.Float(), nullable=True),
        sa.Column("free_share", sa.Float(), nullable=True),
        sa.Column("turnover_rate", sa.Float(), nullable=True),
        sa.Column("turnover_rate_f", sa.Float(), nullable=True),
        sa.Column("volume_ratio", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint(
            "ts_code", "trade_date", name=op.f("pk_daily_indicators"),
        ),
    )
    with op.batch_alter_table("daily_indicators", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_daily_indicators_trade_date"), ["trade_date"], unique=False,
        )

    op.create_table(
        "daily_quotes",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("trade_date", sa.String(), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("pre_close", sa.Float(), nullable=True),
        sa.Column("change", sa.Float(), nullable=True),
        sa.Column("pct_chg", sa.Float(), nullable=True),
        sa.Column("vol", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("adj_factor", sa.Float(), nullable=True),
        sa.Column("qfq_open", sa.Float(), nullable=True),
        sa.Column("qfq_high", sa.Float(), nullable=True),
        sa.Column("qfq_low", sa.Float(), nullable=True),
        sa.Column("qfq_close", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("ts_code", "trade_date", name=op.f("pk_daily_quotes")),
    )
    with op.batch_alter_table("daily_quotes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_daily_quotes_trade_date"), ["trade_date"], unique=False,
        )

    op.create_table(
        "dividend",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("end_date", sa.String(), nullable=False),
        sa.Column("ann_date", sa.String(), nullable=False),
        sa.Column("div_proc", sa.String(), nullable=True),
        sa.Column("stk_div", sa.Float(), nullable=True),
        sa.Column("stk_bo_rate", sa.Float(), nullable=True),
        sa.Column("stk_co_rate", sa.Float(), nullable=True),
        sa.Column("cash_div_tax", sa.Float(), nullable=True),
        sa.Column("cash_div_tax_rate", sa.Float(), nullable=True),
        sa.Column("record_date", sa.String(), nullable=True),
        sa.Column("ex_date", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint(
            "ts_code", "end_date", "ann_date", name=op.f("pk_dividend"),
        ),
    )
    with op.batch_alter_table("dividend", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dividend_ann_date"), ["ann_date"], unique=False,
        )

    op.create_table(
        "fina_audit",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("end_date", sa.String(), nullable=False),
        sa.Column("ann_date", sa.String(), nullable=True),
        sa.Column("audit_result", sa.String(), nullable=True),
        sa.Column("audit_fees", sa.Float(), nullable=True),
        sa.Column("audit_agency", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("ts_code", "end_date", name=op.f("pk_fina_audit")),
    )
    op.create_table(
        "fina_forecast",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("end_date", sa.String(), nullable=False),
        sa.Column("ann_date", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("p_change_min", sa.Float(), nullable=True),
        sa.Column("p_change_max", sa.Float(), nullable=True),
        sa.Column("net_profit_min", sa.Float(), nullable=True),
        sa.Column("net_profit_max", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint(
            "ts_code", "end_date", "ann_date", name=op.f("pk_fina_forecast"),
        ),
    )
    with op.batch_alter_table("fina_forecast", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fina_forecast_ann_date"), ["ann_date"], unique=False,
        )

    op.create_table(
        "fina_mainbz",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("end_date", sa.String(), nullable=False),
        sa.Column("bz_item", sa.String(), nullable=False),
        sa.Column("bz_sales", sa.Float(), nullable=True),
        sa.Column("bz_profit", sa.Float(), nullable=True),
        sa.Column("bz_cost", sa.Float(), nullable=True),
        sa.Column("curr_type", sa.String(), nullable=True),
        sa.Column("update_flag", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint(
            "ts_code", "end_date", "bz_item", name=op.f("pk_fina_mainbz"),
        ),
    )
    with op.batch_alter_table("fina_mainbz", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fina_mainbz_end_date"), ["end_date"], unique=False,
        )

    op.create_table(
        "financial_reports",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("end_date", sa.String(), nullable=False),
        sa.Column("ann_date", sa.String(), nullable=True),
        sa.Column("report_type", sa.String(), nullable=True),
        sa.Column("total_revenue", sa.Float(), nullable=True),
        sa.Column("revenue", sa.Float(), nullable=True),
        sa.Column("n_income", sa.Float(), nullable=True),
        sa.Column("n_income_attr_p", sa.Float(), nullable=True),
        sa.Column("total_assets", sa.Float(), nullable=True),
        sa.Column("total_liab", sa.Float(), nullable=True),
        sa.Column("total_hldr_eqy_exc_min_int", sa.Float(), nullable=True),
        sa.Column("roe", sa.Float(), nullable=True),
        sa.Column("roe_dt", sa.Float(), nullable=True),
        sa.Column("grossprofit_margin", sa.Float(), nullable=True),
        sa.Column("netprofit_margin", sa.Float(), nullable=True),
        sa.Column("debt_to_assets", sa.Float(), nullable=True),
        sa.Column("or_yoy", sa.Float(), nullable=True),
        sa.Column("netprofit_yoy", sa.Float(), nullable=True),
        sa.Column("goodwill", sa.Float(), nullable=True),
        sa.Column("audit_result", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint(
            "ts_code", "end_date", name=op.f("pk_financial_reports"),
        ),
    )
    with op.batch_alter_table("financial_reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_financial_reports_end_date"), ["end_date"], unique=False,
        )

    op.create_table(
        "index_daily",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("trade_date", sa.String(), nullable=False),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("pre_close", sa.Float(), nullable=True),
        sa.Column("change", sa.Float(), nullable=True),
        sa.Column("pct_chg", sa.Float(), nullable=True),
        sa.Column("vol", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("ts_code", "trade_date", name=op.f("pk_index_daily")),
    )
    with op.batch_alter_table("index_daily", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_index_daily_trade_date"), ["trade_date"], unique=False,
        )

    op.create_table(
        "index_dailybasic",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("trade_date", sa.String(), nullable=False),
        sa.Column("total_mv", sa.Float(), nullable=True),
        sa.Column("float_mv", sa.Float(), nullable=True),
        sa.Column("total_share", sa.Float(), nullable=True),
        sa.Column("float_share", sa.Float(), nullable=True),
        sa.Column("free_share", sa.Float(), nullable=True),
        sa.Column("turnover_rate", sa.Float(), nullable=True),
        sa.Column("turnover_rate_f", sa.Float(), nullable=True),
        sa.Column("pe", sa.Float(), nullable=True),
        sa.Column("pe_ttm", sa.Float(), nullable=True),
        sa.Column("pb", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint(
            "ts_code", "trade_date", name=op.f("pk_index_dailybasic"),
        ),
    )
    op.create_table(
        "index_weight",
        sa.Column("index_code", sa.String(), nullable=False),
        sa.Column("con_code", sa.String(), nullable=False),
        sa.Column("trade_date", sa.String(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint(
            "index_code", "con_code", "trade_date", name=op.f("pk_index_weight"),
        ),
    )
    with op.batch_alter_table("index_weight", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_index_weight_trade_date"), ["trade_date"], unique=False,
        )

    op.create_table(
        "limit_list",
        sa.Column("trade_date", sa.String(), nullable=False),
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("pct_chg", sa.Float(), nullable=True),
        sa.Column("amp", sa.Float(), nullable=True),
        sa.Column("fc_ratio", sa.Float(), nullable=True),
        sa.Column("fl_ratio", sa.Float(), nullable=True),
        sa.Column("fd_amount", sa.Float(), nullable=True),
        sa.Column("first_time", sa.String(), nullable=True),
        sa.Column("last_time", sa.String(), nullable=True),
        sa.Column("open_times", sa.Integer(), nullable=True),
        sa.Column("strth", sa.Float(), nullable=True),
        sa.Column("limit_type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("trade_date", "ts_code", name=op.f("pk_limit_list")),
    )
    with op.batch_alter_table("limit_list", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_limit_list_ts_code"), ["ts_code"], unique=False,
        )

    op.create_table(
        "macro_economy",
        sa.Column("period", sa.String(), nullable=False),
        sa.Column("m2", sa.Float(), nullable=True),
        sa.Column("m2_yoy", sa.Float(), nullable=True),
        sa.Column("m1", sa.Float(), nullable=True),
        sa.Column("m1_yoy", sa.Float(), nullable=True),
        sa.Column("m0", sa.Float(), nullable=True),
        sa.Column("m0_yoy", sa.Float(), nullable=True),
        sa.Column("cpi", sa.Float(), nullable=True),
        sa.Column("ppi", sa.Float(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("period", name=op.f("pk_macro_economy")),
    )
    op.create_table(
        "margin_daily",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("trade_date", sa.String(), nullable=False),
        sa.Column("rzye", sa.Float(), nullable=True),
        sa.Column("rqye", sa.Float(), nullable=True),
        sa.Column("rzmre", sa.Float(), nullable=True),
        sa.Column("rqyl", sa.Float(), nullable=True),
        sa.Column("rzrqye", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("ts_code", "trade_date", name=op.f("pk_margin_daily")),
    )
    with op.batch_alter_table("margin_daily", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_margin_daily_trade_date"), ["trade_date"], unique=False,
        )

    op.create_table(
        "market_news",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("tags", sa.String(), nullable=True),
        sa.Column("publish_time", sa.String(), nullable=True),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_news")),
        sa.UniqueConstraint(
            "content", "publish_time", name="uq_market_news_content_pub",
        ),
    )
    op.create_table(
        "moneyflow_daily",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("trade_date", sa.String(), nullable=False),
        sa.Column("buy_sm_vol", sa.Integer(), nullable=True),
        sa.Column("buy_sm_amount", sa.Float(), nullable=True),
        sa.Column("sell_sm_vol", sa.Integer(), nullable=True),
        sa.Column("sell_sm_amount", sa.Float(), nullable=True),
        sa.Column("buy_md_vol", sa.Integer(), nullable=True),
        sa.Column("buy_md_amount", sa.Float(), nullable=True),
        sa.Column("sell_md_vol", sa.Integer(), nullable=True),
        sa.Column("sell_md_amount", sa.Float(), nullable=True),
        sa.Column("buy_lg_vol", sa.Integer(), nullable=True),
        sa.Column("buy_lg_amount", sa.Float(), nullable=True),
        sa.Column("sell_lg_vol", sa.Integer(), nullable=True),
        sa.Column("sell_lg_amount", sa.Float(), nullable=True),
        sa.Column("buy_elg_vol", sa.Integer(), nullable=True),
        sa.Column("buy_elg_amount", sa.Float(), nullable=True),
        sa.Column("sell_elg_vol", sa.Integer(), nullable=True),
        sa.Column("sell_elg_amount", sa.Float(), nullable=True),
        sa.Column("net_mf_vol", sa.Integer(), nullable=True),
        sa.Column("net_mf_amount", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint(
            "ts_code", "trade_date", name=op.f("pk_moneyflow_daily"),
        ),
    )
    with op.batch_alter_table("moneyflow_daily", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_moneyflow_daily_trade_date"), ["trade_date"], unique=False,
        )

    op.create_table(
        "moneyflow_hsgt",
        sa.Column("trade_date", sa.String(), nullable=False),
        sa.Column("ggt_ss", sa.Float(), nullable=True),
        sa.Column("ggt_sz", sa.Float(), nullable=True),
        sa.Column("hgt", sa.Float(), nullable=True),
        sa.Column("sgt", sa.Float(), nullable=True),
        sa.Column("north_money", sa.Float(), nullable=True),
        sa.Column("south_money", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("trade_date", name=op.f("pk_moneyflow_hsgt")),
    )
    op.create_table(
        "northbound_holding",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("trade_date", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("vol", sa.Integer(), nullable=True),
        sa.Column("ratio", sa.Float(), nullable=True),
        sa.Column("exchange", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint(
            "ts_code", "trade_date", name=op.f("pk_northbound_holding"),
        ),
    )
    with op.batch_alter_table("northbound_holding", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_northbound_holding_trade_date"), ["trade_date"], unique=False,
        )

    op.create_table(
        "pledge_stat",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("end_date", sa.String(), nullable=False),
        sa.Column("pledge_count", sa.Integer(), nullable=True),
        sa.Column("unrest_pledge", sa.Float(), nullable=True),
        sa.Column("rest_pledge", sa.Float(), nullable=True),
        sa.Column("total_share", sa.Float(), nullable=True),
        sa.Column("pledge_ratio", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("ts_code", "end_date", name=op.f("pk_pledge_stat")),
    )
    op.create_table(
        "repurchase",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("ann_date", sa.String(), nullable=False),
        sa.Column("end_date", sa.String(), nullable=True),
        sa.Column("proc", sa.String(), nullable=True),
        sa.Column("exp_date", sa.String(), nullable=True),
        sa.Column("vol", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("high_limit", sa.Float(), nullable=True),
        sa.Column("low_limit", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("ts_code", "ann_date", name=op.f("pk_repurchase")),
    )
    with op.batch_alter_table("repurchase", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_repurchase_ann_date"), ["ann_date"], unique=False,
        )

    op.create_table(
        "screening_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trade_date", sa.String(), nullable=False),
        sa.Column("strategy_name", sa.String(), nullable=False),
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("pct_chg", sa.Float(), nullable=True),
        sa.Column("industry", sa.String(), nullable=True),
        sa.Column("vol", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("turnover_rate", sa.Float(), nullable=True),
        sa.Column("pe_ttm", sa.Float(), nullable=True),
        sa.Column("pb", sa.Float(), nullable=True),
        sa.Column("ps_ttm", sa.Float(), nullable=True),
        sa.Column("dv_ttm", sa.Float(), nullable=True),
        sa.Column("total_mv", sa.Float(), nullable=True),
        sa.Column("circ_mv", sa.Float(), nullable=True),
        sa.Column("roe", sa.Float(), nullable=True),
        sa.Column("grossprofit_margin", sa.Float(), nullable=True),
        sa.Column("debt_to_assets", sa.Float(), nullable=True),
        sa.Column("or_yoy", sa.Float(), nullable=True),
        sa.Column("netprofit_yoy", sa.Float(), nullable=True),
        sa.Column("t1_price", sa.Float(), nullable=True),
        sa.Column("t1_pct", sa.Float(), nullable=True),
        sa.Column("t5_price", sa.Float(), nullable=True),
        sa.Column("t5_pct", sa.Float(), nullable=True),
        sa.Column("ai_score", sa.Integer(), nullable=True),
        sa.Column("ai_reason", sa.String(), nullable=True),
        sa.Column("thinking", sa.String(), nullable=True),
        sa.Column("prediction_result", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_screening_history")),
        sa.UniqueConstraint(
            "trade_date",
            "strategy_name",
            "ts_code",
            name="uq_screening_history_date_strategy_code",
        ),
    )
    with op.batch_alter_table("screening_history", schema=None) as batch_op:
        batch_op.create_index(
            "idx_sh_date_strategy", ["trade_date", "strategy_name"], unique=False,
        )

    op.create_table(
        "shibor_daily",
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("on", sa.Float(), nullable=True),
        sa.Column("1w", sa.Float(), nullable=True),
        sa.Column("2w", sa.Float(), nullable=True),
        sa.Column("1m", sa.Float(), nullable=True),
        sa.Column("3m", sa.Float(), nullable=True),
        sa.Column("6m", sa.Float(), nullable=True),
        sa.Column("9m", sa.Float(), nullable=True),
        sa.Column("1y", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("date", name=op.f("pk_shibor_daily")),
    )
    op.create_table(
        "stk_holdernumber",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("end_date", sa.String(), nullable=False),
        sa.Column("ann_date", sa.String(), nullable=True),
        sa.Column("holder_num", sa.Integer(), nullable=True),
        sa.Column("holder_num_change", sa.Float(), nullable=True),
        sa.Column("holder_num_ratio", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint(
            "ts_code", "end_date", name=op.f("pk_stk_holdernumber"),
        ),
    )
    with op.batch_alter_table("stk_holdernumber", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stk_holdernumber_end_date"), ["end_date"], unique=False,
        )

    op.create_table(
        "stock_basic",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("area", sa.String(), nullable=True),
        sa.Column("industry", sa.String(), nullable=True),
        sa.Column("market", sa.String(), nullable=True),
        sa.Column("list_date", sa.String(), nullable=True),
        sa.Column("list_status", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("ts_code", name=op.f("pk_stock_basic")),
    )
    with op.batch_alter_table("stock_basic", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stock_basic_list_date"), ["list_date"], unique=False,
        )

    op.create_table(
        "stock_concepts",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("concept_name", sa.String(), nullable=True),
        sa.Column("concept_id", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint(
            "ts_code", "concept_id", name=op.f("pk_stock_concepts"),
        ),
    )
    with op.batch_alter_table("stock_concepts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stock_concepts_ts_code"), ["ts_code"], unique=False,
        )

    op.create_table(
        "stock_sync_status",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("step4_completed_at", sa.String(), nullable=True),
        sa.Column("sync_version", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("ts_code", name=op.f("pk_stock_sync_status")),
    )
    op.create_table(
        "suspend_d",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("trade_date", sa.String(), nullable=False),
        sa.Column("suspend_timing", sa.String(), nullable=True),
        sa.Column("suspend_type_name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("ts_code", "trade_date", name=op.f("pk_suspend_d")),
    )
    with op.batch_alter_table("suspend_d", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_suspend_d_trade_date"), ["trade_date"], unique=False,
        )

    op.create_table(
        "sync_status",
        sa.Column("table_name", sa.String(), nullable=False),
        sa.Column("last_sync_date", sa.String(), nullable=True),
        sa.Column("last_data_date", sa.String(), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("table_name", name=op.f("pk_sync_status")),
    )
    op.create_table(
        "task_history",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("task_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("error", sa.String(), nullable=True),
        sa.Column("result", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("started_at", sa.String(), nullable=True),
        sa.Column("completed_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task_history")),
    )
    with op.batch_alter_table("task_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_task_history_created_at"), ["created_at"], unique=False,
        )

    op.create_table(
        "top10_holders",
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("end_date", sa.String(), nullable=False),
        sa.Column("ann_date", sa.String(), nullable=True),
        sa.Column("holder_name", sa.String(), nullable=False),
        sa.Column("hold_amount", sa.Float(), nullable=True),
        sa.Column("hold_ratio", sa.Float(), nullable=True),
        sa.Column("holder_type", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint(
            "ts_code", "end_date", "holder_name", name=op.f("pk_top10_holders"),
        ),
    )
    with op.batch_alter_table("top10_holders", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_top10_holders_holder_name"), ["holder_name"], unique=False,
        )

    op.create_table(
        "top_list",
        sa.Column("trade_date", sa.String(), nullable=False),
        sa.Column("ts_code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("pct_chg", sa.Float(), nullable=True),
        sa.Column("turnover_rate", sa.Float(), nullable=True),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column("l_sell", sa.Float(), nullable=True),
        sa.Column("l_buy", sa.Float(), nullable=True),
        sa.Column("l_amount", sa.Float(), nullable=True),
        sa.Column("net_amount", sa.Float(), nullable=True),
        sa.Column("net_rate", sa.Float(), nullable=True),
        sa.Column("amount_rate", sa.Float(), nullable=True),
        sa.Column("float_values", sa.Float(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("trade_date", "ts_code", name=op.f("pk_top_list")),
    )
    with op.batch_alter_table("top_list", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_top_list_ts_code"), ["ts_code"], unique=False,
        )

    op.create_table(
        "trade_cal",
        sa.Column("cal_date", sa.String(), nullable=False),
        sa.Column("exchange", sa.String(), nullable=True),
        sa.Column("is_open", sa.Integer(), nullable=True),
        sa.Column("pretrade_date", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("cal_date", name=op.f("pk_trade_cal")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("trade_cal")
    with op.batch_alter_table("top_list", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_top_list_ts_code"))

    op.drop_table("top_list")
    with op.batch_alter_table("top10_holders", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_top10_holders_holder_name"))

    op.drop_table("top10_holders")
    with op.batch_alter_table("task_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_history_created_at"))

    op.drop_table("task_history")
    op.drop_table("sync_status")
    with op.batch_alter_table("suspend_d", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_suspend_d_trade_date"))

    op.drop_table("suspend_d")
    op.drop_table("stock_sync_status")
    with op.batch_alter_table("stock_concepts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stock_concepts_ts_code"))

    op.drop_table("stock_concepts")
    with op.batch_alter_table("stock_basic", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stock_basic_list_date"))

    op.drop_table("stock_basic")
    with op.batch_alter_table("stk_holdernumber", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stk_holdernumber_end_date"))

    op.drop_table("stk_holdernumber")
    op.drop_table("shibor_daily")
    with op.batch_alter_table("screening_history", schema=None) as batch_op:
        batch_op.drop_index("idx_sh_date_strategy")

    op.drop_table("screening_history")
    with op.batch_alter_table("repurchase", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_repurchase_ann_date"))

    op.drop_table("repurchase")
    op.drop_table("pledge_stat")
    with op.batch_alter_table("northbound_holding", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_northbound_holding_trade_date"))

    op.drop_table("northbound_holding")
    op.drop_table("moneyflow_hsgt")
    with op.batch_alter_table("moneyflow_daily", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_moneyflow_daily_trade_date"))

    op.drop_table("moneyflow_daily")
    op.drop_table("market_news")
    with op.batch_alter_table("margin_daily", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_margin_daily_trade_date"))

    op.drop_table("margin_daily")
    op.drop_table("macro_economy")
    with op.batch_alter_table("limit_list", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_limit_list_ts_code"))

    op.drop_table("limit_list")
    with op.batch_alter_table("index_weight", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_index_weight_trade_date"))

    op.drop_table("index_weight")
    op.drop_table("index_dailybasic")
    with op.batch_alter_table("index_daily", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_index_daily_trade_date"))

    op.drop_table("index_daily")
    with op.batch_alter_table("financial_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_financial_reports_end_date"))

    op.drop_table("financial_reports")
    with op.batch_alter_table("fina_mainbz", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fina_mainbz_end_date"))

    op.drop_table("fina_mainbz")
    with op.batch_alter_table("fina_forecast", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fina_forecast_ann_date"))

    op.drop_table("fina_forecast")
    op.drop_table("fina_audit")
    with op.batch_alter_table("dividend", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dividend_ann_date"))

    op.drop_table("dividend")
    with op.batch_alter_table("daily_quotes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_quotes_trade_date"))

    op.drop_table("daily_quotes")
    with op.batch_alter_table("daily_indicators", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_indicators_trade_date"))

    op.drop_table("daily_indicators")
    op.drop_table("block_trade")
    with op.batch_alter_table("adj_factor", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_adj_factor_trade_date"))

    op.drop_table("adj_factor")
    # ### end Alembic commands ###
