"""remove cash_div_tax_rate

Revision ID: 594852650faa
Revises: f142c19ebce7
Create Date: 2026-03-12 21:22:29.650153

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '594852650faa'
down_revision: Union[str, Sequence[str], None] = 'f142c19ebce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dividend', 'cash_div_tax_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dividend', sa.Column('cash_div_tax_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
