"""真实 sidecar + 真实 PG 的 Alembic 迁移回归集成测试。

覆盖 spec §3.3：embedded 模式迁移回归（upgrade head / downgrade base / upgrade head / check）。

验证 sidecar bundled PG 17 与 alembic 迁移脚本完全兼容。

依赖：
- ``real_embedded_pg`` fixture（session-scoped 真实 PG 实例）
- ``make_alembic_cfg`` / ``create_test_engine`` from ``tests._helpers``

标记：
- ``pytest.mark.integration``
- ``pytest.mark.embedded_real``

隔离策略：
- 每个测试前 ``DROP SCHEMA public CASCADE`` + ``CREATE SCHEMA public``（清除所有表和 alembic_version 表）
- 确保每个测试从干净状态开始，顺序无关（pytest-randomly 安全）

loop_scope：
- 所有 async 测试用 ``loop_scope="session"``（对齐 ``real_embedded_pg`` session fixture）
"""

# pyright: reportPrivateUsage=false

from __future__ import annotations

import asyncio

import pytest
from alembic import command
from sqlalchemy import text

from data.persistence.embedded_postgres.protocol import ConnectionInfo
from tests._helpers import create_test_engine, make_alembic_cfg

pytestmark = [pytest.mark.integration, pytest.mark.embedded_real]


async def _reset_schema(url: str) -> None:
    """重置 public schema：DROP CASCADE + CREATE，清除所有表和 alembic_version 表。

    确保每个测试从干净状态开始。sidecar 创建的 DB owner（qtrading）有权限 DROP public schema。
    """
    engine = create_test_engine(url)
    try:
        async with engine.begin() as conn:
            await conn.execute(text("DROP SCHEMA IF EXISTS public CASCADE"))
            await conn.execute(text("CREATE SCHEMA public"))
    finally:
        await engine.dispose()


async def _get_table_names(url: str) -> set[str]:
    """获取 public schema 的所有表名。"""
    engine = create_test_engine(url)
    try:
        async with engine.connect() as conn:
            result = await conn.execute(
                text("SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'")
            )
            return {row[0] for row in result}
    finally:
        await engine.dispose()


class TestEmbeddedPgMigrationRegression:
    """embedded PG Alembic 迁移回归测试。

    env.py 自动将 ``postgresql+asyncpg://`` URL 转为 ``postgresql://`` sync URL
    （alembic/env.py:69），因此 ``make_alembic_cfg(info.url)`` 直接传入 async URL 即可。
    """

    @pytest.mark.asyncio(loop_scope="session")
    async def test_embedded_pg_alembic_upgrade_head(self, real_embedded_pg: ConnectionInfo) -> None:
        """``upgrade head`` 成功，业务表（如 stock_basic）和 alembic_version 表已创建。"""
        info = real_embedded_pg
        await _reset_schema(info.url)

        cfg = make_alembic_cfg(info.url)
        await asyncio.to_thread(command.upgrade, cfg, "head")

        tables = await _get_table_names(info.url)
        assert "stock_basic" in tables, f"stock_basic table not found after upgrade head: {tables}"
        assert "alembic_version" in tables

    @pytest.mark.asyncio(loop_scope="session")
    async def test_embedded_pg_alembic_downgrade_base(self, real_embedded_pg: ConnectionInfo) -> None:
        """``downgrade base`` 成功，业务表和 alembic_version 表全部删除。"""
        info = real_embedded_pg
        await _reset_schema(info.url)

        cfg = make_alembic_cfg(info.url)
        # 先 upgrade head，再 downgrade base
        await asyncio.to_thread(command.upgrade, cfg, "head")
        await asyncio.to_thread(command.downgrade, cfg, "base")

        tables = await _get_table_names(info.url)
        # base 状态：无业务表，无 alembic_version 表
        assert "stock_basic" not in tables
        assert "alembic_version" not in tables

    @pytest.mark.asyncio(loop_scope="session")
    async def test_embedded_pg_alembic_upgrade_head_after_downgrade(self, real_embedded_pg: ConnectionInfo) -> None:
        """``downgrade base`` 后再 ``upgrade head``（幂等），业务表重新创建。"""
        info = real_embedded_pg
        await _reset_schema(info.url)

        cfg = make_alembic_cfg(info.url)
        await asyncio.to_thread(command.upgrade, cfg, "head")
        await asyncio.to_thread(command.downgrade, cfg, "base")
        # 再 upgrade head（幂等验证）
        await asyncio.to_thread(command.upgrade, cfg, "head")

        tables = await _get_table_names(info.url)
        assert "stock_basic" in tables, f"stock_basic table not found after upgrade-downgrade-upgrade: {tables}"
        assert "alembic_version" in tables

    @pytest.mark.asyncio(loop_scope="session")
    async def test_embedded_pg_alembic_check(self, real_embedded_pg: ConnectionInfo) -> None:
        """``alembic check`` 无异常（schema 与迁移头一致）。

        ``alembic check`` 在 schema 与迁移头不一致时抛 ``AutogenerateDiffsDetected``；
        upgrade head 后 schema 应与迁移头一致，check 通过。
        """
        info = real_embedded_pg
        await _reset_schema(info.url)

        cfg = make_alembic_cfg(info.url)
        await asyncio.to_thread(command.upgrade, cfg, "head")

        # 无异常即通过
        await asyncio.to_thread(command.check, cfg)
