name: OpenSSF Scorecard

on:
  branch_protection_rule:
  schedule:
    - cron: "0 6 * * 1"
  push:
    branches: [main]
  workflow_dispatch:

permissions: read-all

jobs:
  analysis:
    name: Scorecard Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      security-events: write
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false

      - name: Run Scorecard Analysis
        uses: ossf/scorecard-action@05c42c7b01a35d6aebb1f63c63f5a15a4512e930  # v2.4.2
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF results to Code Scanning
        uses: github/codeql-action/upload-sarif@fca7ace96b7d713c7035871441bd52efbe39e27e  # v3.28.19
        with:
          sarif_file: results.sarif
